---
- name: Configure main config (Linux)
  template:
    src: config.yaml.j2
    dest: "{{ swisnap_main_config_path }}"
    owner: "{{ swisnap_user }}"
    group: "{{ swisnap_user_group }}"
    mode: 0640
  notify: Restart Linux service
  become: yes
  when: ansible_os_family != "Windows"

- name: Configure publisher AppOptics config file (Linux)
  template:
    src: publisher-appoptics.yaml.j2
    dest: "{{ swinsap_publisher_appoptics_path }}"
    owner: "{{ swisnap_user }}"
    group: "{{ swisnap_user_group }}"
    mode: 0640
  notify: Restart Linux service
  become: yes
  when: ansible_os_family != "Windows"

- name: Configure publisher processes config file (Linux)
  template:
    src: publisher-processes.yaml.j2
    dest: "{{ swinsap_processes_appoptics_path }}"
    owner: "{{ swisnap_user }}"
    group: "{{ swisnap_user_group }}"
    mode: 0640
  notify: Restart Linux service
  become: yes
  when: ansible_os_family != "Windows"

- name: Configure main config (Windows)
  win_template:
    src: config.yaml.j2
    dest: "{{ swisnap_main_config_path }}"
  notify: Restart Windows service
  when: ansible_os_family == "Windows"

- name: Configure publisher AppOptics config file (Windows)
  win_template:
    src: publisher-appoptics.yaml.j2
    dest: "{{ swinsap_publisher_appoptics_path }}"
  notify: Restart Windows service
  when: ansible_os_family == "Windows"

- name: Configure publisher processes config file (Windows)
  win_template:
    src: publisher-processes.yaml.j2
    dest: "{{ swinsap_processes_appoptics_path }}"
  notify: Restart Windows service
  when: ansible_os_family == "Windows"

- name: Copy V1 tasks (Linux)
  copy:
    src: "{{ swisnap_custom_v1_task_path }}/"
    dest: "{{ swisnap_task_path }}"
    owner: "{{ swisnap_user }}"
    group: "{{ swisnap_user_group }}"
    mode: 0640
  notify: Restart Linux service
  become: yes
  when:
    - swisnap_custom_v1_task_path | length > 0
    - ansible_os_family != "Windows"

- name: Copy V2 tasks (Linux)
  copy:
    src: "{{ swisnap_custom_v2_task_path }}/"
    dest: "{{ swisnap_tasks_autoload_path }}"
    owner: "{{ swisnap_user }}"
    group: "{{ swisnap_user_group }}"
    mode: 0640
  notify: Restart Linux service
  become: yes
  when:
    - swisnap_custom_v2_task_path | length > 0
    - ansible_os_family != "Windows"

- name: Copy plugin configs (Linux)
  copy:
    src: "{{ swisnap_custom_plugin_configs_path }}/"
    dest: "{{ swisnap_plugins_config }}"
    owner: "{{ swisnap_user }}"
    group: "{{ swisnap_user_group }}"
    mode: 0640
  notify: Restart Linux service
  become: yes
  when:
    - swisnap_custom_plugin_configs_path | length > 0
    - ansible_os_family != "Windows"

- name: Copy V1 tasks (Windows)
  win_copy:
    src: "{{ swisnap_custom_v1_task_path }}/"
    dest: "{{ swisnap_task_path }}"
  notify: Restart Windows service
  when:
    - swisnap_custom_v1_task_path | length > 0
    - ansible_os_family == "Windows"

- name: Copy V2 tasks (Windows)
  win_copy:
    src: "{{ swisnap_custom_v2_task_path }}/"
    dest: "{{ swisnap_tasks_autoload_path }}"
  notify: Restart Windows service
  when:
    - swisnap_custom_v2_task_path | length > 0
    - ansible_os_family == "Windows"

- name: Copy plugin configs (Windows)
  win_copy:
    src: "{{ swisnap_custom_plugin_configs_path }}/"
    dest: "{{ swisnap_plugins_config }}"
  notify: Restart Windows service
  when:
    - swisnap_custom_plugin_configs_path | length > 0
    - ansible_os_family == "Windows"
