---
version: 2.1
commands:
  run_tests:
    description: "Run molecule tests"
    steps:
      - checkout

      - run:
          name: "Install python 3.8.3"
          command: |
            git version
            (cd $(pyenv root) && git pull origin master)
            pyenv install 3.8.3

      - run:
          name: "Set Python Version"
          command: pyenv global 3.8.3

      - run:
          name: "Install requirements"
          command: pip install -r molecule/requirements.txt

      - run:
          name: "Run tests"
          command: molecule test --all

jobs:
  centos8-container:
    docker:
      - image: centos:centos8
    steps:
      - run: echo "1"

  debian8:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: debian:8
    steps:
      - run_tests

  debian9:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: debian:9
    steps:
      - run_tests

  debian10:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: debian:10
    steps:
      - run_tests

  ubuntu-xenial:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: ubuntu:xenial
    steps:
      - run_tests

  ubuntu-bionic:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: ubuntu:bionic
    steps:
      - run_tests

  ubuntu-focal:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: ubuntu:focal
    steps:
      - run_tests

  centos7:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: centos:7
    steps:
      - run_tests

  centos8:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: centos:8
    steps:
      - run_tests

  amazonlinux1:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: amazonlinux:1
    steps:
      - run_tests

  amazonlinux2:
    machine:
      image: ubuntu-2004:current
    environment:
      PLATFORM: amazonlinux:2
    steps:
      - run_tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - debian8
      - debian9
      - debian10
      - ubuntu-xenial
      - ubuntu-bionic
      - ubuntu-focal
      - centos7
      - centos8
      - amazonlinux1
      - amazonlinux2
      - centos8-container
