---
version: 2.1
commands:
  run_tests:
    description: "Run molecule tests"
    steps:
      - checkout

      - run:
          name: install python 3.8.3
          command: |
            (cd $(pyenv root) && git pull)
            pyenv install 3.8.3

      - run:
          name: "Set Python Version"
          command: pyenv global 3.8.3

      - run:
          name: run tests
          command: pip install -r molecule/requirements.txt

      - run:
          name: run tests
          command: molecule test --all

jobs:
  debian8:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PLATFORM: debian:8
    steps:
    - run_tests

  ubuntu-xenial:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PLATFORM: ubuntu:xenial
    steps:
      - run_tests

  ubuntu-bionic:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      PLATFORM: ubuntu:bionic
    steps:
      - run_tests

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - debian8
      - ubuntu-xenial
      - ubuntu-bionic
