---
- name: Restart Linux service
  ansible.builtin.service:
    name: "{{ swisnap_service }}"
    state: restarted
  become: true

- name: Restart Windows service
  ansible.builtin.win_service:
    name: "{{ swisnap_service }}"
    state: restarted
